### ISSUE TITLE
about zerodivisionerror

### ISSUE THREAD

**Issue by JasonYorkPig** [amineHorseman/facial-expression-recognition-using-cnn#18]
hello amine!
I tried to train 5 emotions with using landmarks.
the train environment is like this:

  - emotions = 5
  - model = B
  - optimizer = 'momentum'
  - learning_rate = 0.016
  - learning_rate_decay = 0.864
  - otimizer_param (momentum) = 0.95
  - keep_prob = 0.956
  - epochs = 100
  - use landmarks = True
  - use hog + landmarks = False
  - use hog sliding window + landmarks = False
  - use batchnorm after conv = True
  - use batchnorm after fc = False_

and I also changed [output_size=5] in parameters.py. but when I tried to train, 

Traceback (most recent call last):
  File "train.py", line 124, in <module>
    train()
  File "train.py", line 60, in train
    n_epoch=TRAINING.epochs)
  File "/anaconda3/envs/tf/lib/python3.6/site-packages/tflearn/models/dnn.py", line 216, in fit
    callbacks=callbacks)
  File "/anaconda3/envs/tf/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 339, in fit
    show_metric)
  File "/anaconda3/envs/tf/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 847, in _train
    e = evaluate_flow(self.session, eval_ops, self.test_dflow)
  File "/anaconda3/envs/tf/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 1003, in evaluate_flow
    res = [r / dataflow.n_samples for r in res]
  File "/anaconda3/envs/tf/lib/python3.6/site-packages/tflearn/helpers/trainer.py", line 1003, in <listcomp>
    res = [r / dataflow.n_samples for r in res]
ZeroDivisionError: float division by zero

Is there anything else that needs to be fixed? :)

**Comment by amineHorseman** [comment]
Can you add a print statement before line 55 to check the size of data['X'], data['X2'] and data['Y']?

**Comment by JasonYorkPig** [comment]
import tensorflow as tf
from tflearn import DNN
import time
import argparse
import os

from data_loader import load_data 
from parameters import DATASET, TRAINING, HYPERPARAMS, NETWORK
from model import build_model

def train(optimizer=HYPERPARAMS.optimizer, optimizer_param=HYPERPARAMS.optimizer_param, 
        learning_rate=HYPERPARAMS.learning_rate, keep_prob=HYPERPARAMS.keep_prob, 
        learning_rate_decay=HYPERPARAMS.learning_rate_decay, decay_step=HYPERPARAMS.decay_step,
        train_model=True):

        print( "loading dataset " + DATASET.name + "...")
        if train_model:
                data, validation = load_data(validation=True)
        else:
                data, validation, test = load_data(validation=True, test=True)

        with tf.Graph().as_default():
                print( "building model...")
                network = build_model(optimizer, optimizer_param, learning_rate, 
                          keep_prob, learning_rate_decay, decay_step)
                model = DNN(network, tensorboard_dir=TRAINING.logs_dir, 
                        tensorboard_verbose=0, checkpoint_path=TRAINING.checkpoint_dir,
                        max_checkpoints=TRAINING.max_checkpoints)

                #tflearn.config.init_graph(seed=None, log_device=False, num_cores=6)

                if train_model:
                        # Training phase
                        print( "start training...")
                        print( "  - emotions = {}".format(NETWORK.output_size))
                        print( "  - model = {}".format(NETWORK.model))
                        print( "  - optimizer = '{}'".format(optimizer))
                        print( "  - learning_rate = {}".format(learning_rate))
                        print( "  - learning_rate_decay = {}".format(learning_rate_decay))
                        print( "  - otimizer_param ({}) = {}".format('beta1' if optimizer == 'adam' else 'momentum', optimizer_param))
                        print( "  - keep_prob = {}".format(keep_prob))
                        print( "  - epochs = {}".format(TRAINING.epochs))
                        print( "  - use landmarks = {}".format(NETWORK.use_landmarks))
                        print( "  - use hog + landmarks = {}".format(NETWORK.use_hog_and_landmarks))
                        print( "  - use hog sliding window + landmarks = {}".format(NETWORK.use_hog_sliding_window_and_landmarks))
                        print( "  - use batchnorm after conv = {}".format(NETWORK.use_batchnorm_after_conv_layers))
                        print( "  - use batchnorm after fc = {}".format(NETWORK.use_batchnorm_after_fully_connected_layers))

                        start_time = time.time()
                        if NETWORK.use_landmarks:
                                model.fit([data['X'], data['X2']], data['Y'],
                                        validation_set=([validation['X'], validation['X2']], validation['Y']),
                                        snapshot_step=TRAINING.snapshot_step,
                                        show_metric=TRAINING.vizualize,
                                        batch_size=TRAINING.batch_size,
                                        n_epoch=TRAINING.epochs)

**Comment by JasonYorkPig** [comment]
What I found was that when I specify the emotions, skip two or more label numbers(0,2,4) then the ZeroDivisionError was happened.

**Comment by LauraKag** [comment]
I have the exact same issue...how can I fix it?
